### ISSUE TITLE
Incorrectly synced users visit logs

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/data-sync#39]
All users with the same email are removed in the data sync. Need to check whether this means their associated logs are removed as well.

Org_id 20 were using anon users with the same email address and need their backdated data.

**Comment by astroash** [comment]
Assuming that this data has not been migrated as `visit` tables `user_account_id` is set to `NOT NULL`.

**Comment by eliasmalik** [comment]
Just off the top of my head, I think the plan was to keep the user accounts, but set the e-mails to null. Check users 455-457, they are (I think) the anonymous users. 

From a first glance at the DB though, there does appear to be something funky going on with the logs though. Can take a look.

**Comment by astroash** [comment]
@eliascodes the accounts in question were not migrated. I searched for the QR code Org_id 20 were using and it existed in the old visitor app db but not in twine-api's one.

qr code: df05ad286e54671d08655f0a122b61e024b8a05b41439d5dd8e53459809bd0d1

**Comment by astroash** [comment]
The emails are set to `null`, then all the accounts are merged as they have the same email.

I'm going to recreate these accounts in the new database, and we can migrate their corresponding data afterwards.

**Comment by eliasmalik** [comment]
> The emails are set to null, then all the accounts are merged as they have the same email.

🤦🏽‍♂️ oops

> I'm going to recreate these accounts in the new database, and we can migrate their corresponding data afterwards.

Sounds good

**Comment by astroash** [comment]
@eliascodes it would be great if you could write a script for manually syncing visit logs from the old db to the new one. Here is the accounts that have been affected and need their logs resetting

## Org 20

The following users were merged with incorrect accounts and need their visit logs on the new db wiped and sync their old logs again. User ids are for new db:
- [ ] user 286 has 35 accounts merged with them.
- [ ] user 527 has 3 accounts merged with them.
- [ ] user 528 has been merged with 1 other account.
- [ ] user 533 has been merged with 1 other account. 
- [ ] user 537 has been merged with 1 other account.

The following accounts were deleted in the merge. Their logs need migrating:
```js
[ { user_account_id: 611 },
  { user_account_id: 613 },
  { user_account_id: 612 },
  { user_account_id: 615 },
  { user_account_id: 614 },
  { user_account_id: 591 },
  { user_account_id: 592 },
  { user_account_id: 573 },
  { user_account_id: 574 },
  { user_account_id: 575 },
  { user_account_id: 576 },
  { user_account_id: 579 },
  { user_account_id: 580 },
  { user_account_id: 581 },
  { user_account_id: 582 },
  { user_account_id: 583 },
  { user_account_id: 584 },
  { user_account_id: 585 },
  { user_account_id: 586 },
  { user_account_id: 587 },
  { user_account_id: 577 },
  { user_account_id: 589 },
  { user_account_id: 578 },
  { user_account_id: 590 },
  { user_account_id: 588 },
  { user_account_id: 593 },
  { user_account_id: 594 },
  { user_account_id: 595 },
  { user_account_id: 606 },
  { user_account_id: 607 },
  { user_account_id: 608 },
  { user_account_id: 609 },
  { user_account_id: 610 },
  { user_account_id: 616 },
  { user_account_id: 617 },
  { user_account_id: 618 },
  { user_account_id: 621 },
  { user_account_id: 622 },
  { user_account_id: 623 } ]
```
## Org 6

Incorrectly synced:
- [ ] { user_account_id: 623 }

Newly created account needing logs:
```
[
 { user_account_id: 624 },
 { user_account_id: 625 },
 { user_account_id: 626 }, 😸
 { user_account_id: 627 },
]
```

EDIT: 

no longer tracking newly created users, but will keep records of users that have had accounts merged with theirs incase it is useful

509, 512

**Comment by eliasmalik** [comment]
Another problem encountered, caused by the redundancy in the original visitor app schema with respect to organisation IDs. There are org IDs in the `visits` table, the `users` table and the `activities` table, and the value of these columns is inconsistent in 73 cases.

To see this, run the following query:
```sql
select
  visits.id as visit_id,
  visits.date,
  activities.name as activity,
  cba.org_name as activity_org,
  cbu.org_name as user_org,
  cbv.org_name as visit_org,
  users.fullName,
  users.email
from visits
  inner join users on (users.id = visits.usersid)
  inner join activities on (activities.id = visits.activitiesid)
  inner join cbusiness cba on (cba.id = activities.cb_id)
  inner join cbusiness cbv on (cbv.id = visits.cb_id)
  inner join cbusiness cbu on (cbu.id = users.cb_id)
where
  users.cb_id <> activities.cb_id
or
  users.cb_id <> visits.cb_id
or
  visits.cb_id <> activities.cb_id;
```
One would expect that the values of `activity_org`, `user_org` and `visit_org` would be the same, but they are not.

Luckily, all these erroneous records look like they're test records, so we can ignore them.

**Comment by astroash** [comment]
@eliascodes cb id inconsistencies may have been caused by this bug https://github.com/TwinePlatform/twine-visitor/issues/440

**Comment by astroash** [comment]
@eliascodes just realised that I have not been checking whether the new accounts I'm creating have volunteer accounts. This means that we may have new users that have two user accounts for each role. I'l check from now on, but it's worth checking through the new db to see if any users have matching fields.

Visitor accounts that need adding to volunteer accounts:
```js
[
 {
  old_visitor_id: 196,
  new_user_id: 90
 },
 {
  old_visitor_id: 226,
  new_user_id: 185
 },
```

**EDIT: DONE**

**Comment by astroash** [comment]
@eliascodes also just noticed that org 6 have `modified_at` date set before their `created_at` date. Looking at the old db the created at is the correct date. Worth looking into whether this was from the data sync or potential error with our api.

**Comment by eliasmalik** [comment]
>  have modified_at date set before their created_at date

Looks like this is because the record in the visitor app only has a "created_at" date and the record in the volunteer app has both, so the "created_at" date was overwritten, but the other one wasn't.

There are 14 records in the organisation table with similar issues, 14 in the community businesses table (obviously), and 14 in the user table. These are the only two tables where there this could be possible.

**Comment by eliascodes** [comment]
FYI I ran the re-migration just now on production, looks like everything went fine. Logged in to a local clone of organisation 20's account and the graphs look like they should (I think).

**Comment by eliasmalik** [comment]
Remaining work before closing

* [x] Check the accounts that had other accounts merged: do the visit logs look sensible compared to the old DB?
* [x] 27 duplicate names in user account (create new issue)

**Comment by eliasmalik** [comment]
Remaining tasks done, closing.
