### ISSUE TITLE
Test database backups

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/data-sync#7]
Test the database backups by doing a test restore:

* [x] Visitor app (TwinePlatform/twine-visitor#428)
* [x] Admin app (TwinePlatform/Twine-Admin)

Document the process. Determine how long heroku backups are kept.

**Comment by astroash** [comment]
@eliascodes why has this been labelled `external-dependency`?

**Comment by eliascodes** [comment]
Because we don't have access to the Twine-Admin database.
