### ISSUE TITLE
Data inconsistencies between admin and visitor apps

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/data-sync#8]
Use this to document inconsistencies in the data between the various twine apps.

These need to be made consistent in the data-mapping stage of the data sync tool.

### Regions
Regions used in [TwinePlatform/Twine-Admin](https://github.com/TwinePlatform/Twine-Admin):
* East Midlands
* East of England
* London
* North East
* North West
* South East
* South West
* West Midlands
* Yorkshire and the Humber

Regions used in [TwinePlatform/twine-visitor](https://github.com/TwinePlatform/twine-visitor):
* North East
* North West
* Midlands
* Wales
* South West
* South East
* Greater London

**Comment by eliascodes** [comment]
@SonjaTwine which, if any, of the above regions are not required?

**Comment by SonjaTwine** [comment]
Thanks for spotting this! Let's keep only the ones on the twine-admin app, and replace the ones in the visitor app.
